---
# tasks file for nextcloud

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  package:
    name: "{{ nextcloud_requirements }}"
    state: present
  notify:
    - restart httpd

- name: place apache configuration
  template:
    src: nextcloud.conf.j2
    dest: "{{ nextcloud_config_directory }}/nextcloud.conf"
    mode: "0644"
  notify:
    - restart httpd

- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop: "{{ nextcloud_sebooleans }}"

- name: install nextcloud
  unarchive:
    src: "{{ nextcloud_archive }}"
    dest: "{{ nextcloud_destination }}"
    remote_src: yes
    owner: "{{ nextcloud_httpd_owner }}"
    group: "{{ nextcloud_httpd_group }}"
    creates: "{{ nextcloud_destination }}/nextcloud"
    mode: "0775"

- name: configure nextcloud
  command: "{{ nextcloud_command }}"
  args:
    creates: "{{ nextcloud_destination }}/nextcloud/data/index.html"
    chdir: "{{ nextcloud_destination }}/nextcloud"
  no_log: yes
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"

- name: set permissions
  file:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ nextcloud_permissions }}"
  loop_control:
    label: "{{ item.name }}"

- name: install nextcloud app
  command: php occ app:install {{ item.name }}
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
    creates: "{{ nextcloud_destination }}/nextcloud/apps/{{ item.name }}"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"
  loop: "{{ nextcloud_apps }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nextcloud_apps is defined

- name: set nextcloud trusted domains
  lineinfile:
    path: "{{ nextcloud_destination }}/nextcloud/config/config.php"
    regexp: "    0 => '"
    line: "    0 => '{{ nextcloud_domain_url }}'"
    mode: "0775"

- name: set redis cache configuration
  lineinfile:
    path: "{{ nextcloud_destination }}/nextcloud/config/config.php"
    line: "{{ item }}"
    mode: "0775"
  loop:
    - "'memcache.distributed' => '\\OC\\Memcache\\Redis',"
    - "'filelocking.enabled' => true,"
    - "'memcache.locking' => '\\OC\\Memcache\\Redis',"
    - "'redis' => [ 'host' => 'localhost', 'port' => 6379, ],"

- name: include parameters
  include_tasks: parameters.yml
  loop: "{{ nextcloud_settings }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nextcloud_settings is defined
