---

- name: set value
  block:
    - name: list value
      ansible.builtin.command: php occ config:app:get {{ item.section }} {{ item.name }} --output yaml
      args:
        chdir: "{{ nextcloud_destination }}/nextcloud"
      register: nextcloud_list_value
      changed_when: no
      become: yes
      become_user: "{{ nextcloud_httpd_owner }}"
      failed_when:
        - nextcloud_list_value.stdout | from_yaml != item.value
  rescue:
    - name: set nextcloud parameter
      ansible.builtin.command: php occ config:app:set {{ item.section }} {{ item.name }} --value {{ item.value }}
      args:
        chdir: "{{ nextcloud_destination }}/nextcloud"
      become: yes
      become_user: "{{ nextcloud_httpd_owner }}"
      notify:
        - set permissions
