---
# handlers file for nextcloud

- name: set nextcloud trusted domains
  lineinfile:
    path: "{{ nextcloud_destination }}/nextcloud/config/config.php"
    regexp: "    0 => '"
    line: "    0 => '{{ nextcloud_domain_url }}'"
    mode: "0644"

- name: remove config.php
  file:
    path: "{{ nextcloud_destination }}/nextcloud/config/config.php"
    state: absent

- name: set permissions
  file:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ nextcloud_permissions }}"
  loop_control:
    label: "{{ item.name }}"
