---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.httpd
    - role: ansible-role-nextcloud
      nextcloud_apps:
        - name: richdocumentscode
