---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    ../../vars/main.yml

  tasks:
    - name: occ check
      command: php occ check
      args:
        chdir: "{{ nextcloud_destination }}/nextcloud"
      changed_when: no
      become: yes
      become_user: "{{ nextcloud_httpd_owner }}"

    - name: get status.php
      ansible.builtin.uri:
        url: "https://{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}/nextcloud/status.php"
        validate_certs: no
      register: nextcloud_get_status_php
      until:
        - nextcloud_get_status_php is succeeded
      retries: 10
